name: calendar_app
description: A minimal calendar app with three screens.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.3.6
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  cloud_firestore: ^5.6.7
  shared_preferences: ^2.1.1
  uuid: ^4.5.1
  sqflite: ^2.3.0
  path: ^1.8.3
  firebase_auth: ^5.5.3
  timezone: ^0.10.1
  permission_handler: ^12.0.0+1
  intl: ^0.20.2
  table_calendar: ^3.0.9
  flutter_local_notifications: ^19.1.0
  device_info_plus: ^11.4.0
  android_intent_plus: ^5.3.0
  googleapis_auth: ^2.0.0
  http: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
