name: calendar_app
description: A minimal calendar app with three screens.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  # State Management
  flutter_riverpod: ^2.3.6
  
  # Local Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.0
  
  # Authentication
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  
  # Notifications
  timezone: ^0.10.1
  permission_handler: ^12.0.0+1
  
  
  # Date & Time
  intl: ^0.20.2
  
  # UI
  table_calendar: ^3.0.9
  
  # Utils
  uuid: ^4.5.1
  flutter_local_notifications: ^19.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
