// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR4gvJyxZDkyDJ_5E8f4S0TEZWKvsM7XA',
    appId: '1:71095223967:web:3c9bc53ddc610e02f2c4aa',
    messagingSenderId: '71095223967',
    projectId: 'calendar-91627',
    authDomain: 'calendar-91627.firebaseapp.com',
    storageBucket: 'calendar-91627.firebasestorage.app',
    measurementId: 'G-TQJ14PVZN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxs3Pn3teH-SNFqOwHAW_RCnWFkI4F2OM',
    appId: '1:71095223967:android:4bec224559ac9cb4f2c4aa',
    messagingSenderId: '71095223967',
    projectId: 'calendar-91627',
    storageBucket: 'calendar-91627.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSIwvXyiNl8yqWnnMi_4gqgdFUDtS3WxI',
    appId: '1:71095223967:ios:e79a79bc38aad3fcf2c4aa',
    messagingSenderId: '71095223967',
    projectId: 'calendar-91627',
    storageBucket: 'calendar-91627.firebasestorage.app',
    iosBundleId: 'com.example.calendarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSIwvXyiNl8yqWnnMi_4gqgdFUDtS3WxI',
    appId: '1:71095223967:ios:e79a79bc38aad3fcf2c4aa',
    messagingSenderId: '71095223967',
    projectId: 'calendar-91627',
    storageBucket: 'calendar-91627.firebasestorage.app',
    iosBundleId: 'com.example.calendarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR4gvJyxZDkyDJ_5E8f4S0TEZWKvsM7XA',
    appId: '1:71095223967:web:f57e01c17a94a9a8f2c4aa',
    messagingSenderId: '71095223967',
    projectId: 'calendar-91627',
    authDomain: 'calendar-91627.firebaseapp.com',
    storageBucket: 'calendar-91627.firebasestorage.app',
    measurementId: 'G-P48LSQB3QP',
  );
}